<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="four_wheel_robot">

  <!-- Body dimensions -->
  <xacro:property name="body_link_x_dim" value="1"/>
  <xacro:property name="body_link_y_dim" value="0.6"/>
  <xacro:property name="body_link_z_dim" value="0.3"/>

  <!-- Wheel dimensions -->
  <xacro:property name="wheel_link_radius" value="0.15"/>
  <xacro:property name="wheel_link_length" value="0.1"/>
  <xacro:property name="wheel_link_z_location" value="-0.1"/>

  <!-- Sensor dimensions -->
  <xacro:property name="sensor_side" value="0.05"/>

  <!-- Material density -->
  <xacro:property name="body_density" value="2710.0"/>
  <xacro:property name="wheel_density" value="2710.0"/>

  <!-- PI Constant -->
  <xacro:property name="pi_const" value="3.14159265"/>

  <!-- Robot body and wheel mass -->
  <xacro:property name="sensor_mass" value="0.5"/>
  <xacro:property name="body_mass" value="${body_density * body_link_x_dim * body_link_y_dim * body_link_z_dim}"/>
  <xacro:property name="wheel_mass" value="${wheel_density * pi_const * wheel_link_radius * wheel_link_radius * wheel_link_length}"/>

  <!-- Moments of inertia of the wheel -->
  <xacro:property name="Iz_wheel" value="${0.5 * wheel_mass * wheel_link_radius * wheel_link_radius}"/>
  <xacro:property name="I_wheel" value="${(1.0/12.0) * wheel_mass * (3.0 * wheel_link_radius * wheel_link_radius + wheel_link_length * wheel_link_length)}"/>

  <!-- Gazebo definitions -->
  <xacro:include filename="$(find robot_model_pkg)/urdf/robot.gazebo"/>

  <!-- Dummy link -->
  <link name="dummy"/>

  <!-- Body link -->
  <link name="body_link">
    <visual>
      <geometry>
        <box size="${body_link_x_dim} ${body_link_y_dim} ${body_link_z_dim}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>

    <collision>
      <geometry>
        <box size="${body_link_x_dim} ${body_link_y_dim} ${body_link_z_dim}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>

    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="${body_mass}"/>
      <inertia 
        ixx="${(1.0/12.0)*body_mass*(body_link_y_dim*body_link_y_dim + body_link_z_dim*body_link_z_dim)}"
        ixy="0" ixz="0"
        iyy="${(1.0/12.0)*body_mass*(body_link_x_dim*body_link_x_dim + body_link_z_dim*body_link_z_dim)}"
        iyz="0"
        izz="${(1.0/12.0)*body_mass*(body_link_y_dim*body_link_y_dim + body_link_x_dim*body_link_x_dim)}"/>
    </inertial>
  </link>

  <!-- Fixed joint between dummy and body -->
  <joint name="dummy_joint" type="fixed">
    <parent link="dummy"/>
    <child link="body_link"/>
  </joint>

  <!-- Wheel macro -->
  <xacro:macro name="wheel" params="name x y z joint_type">
    <link name="${name}">
  <visual>
    <geometry>
      <cylinder radius="${wheel_link_radius}" length="${wheel_link_length}"/>
    </geometry>
    <origin rpy="0 1.5707 0" xyz="0 0 0"/>
  </visual>
  <collision>
    <geometry>
      <cylinder radius="${wheel_link_radius}" length="${wheel_link_length}"/>
    </geometry>
    <origin rpy="0 1.5707 0" xyz="0 0 0"/>
  </collision>
  <inertial>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <mass value="${wheel_mass}"/>
    <inertia
      ixx="${I_wheel}"
      ixy="0.0" ixz="0.0"
      iyy="${Iz_wheel}"
      iyz="0.0"
      izz="${I_wheel}"/>
  </inertial>
</link>

<joint name="${name}_joint" type="${joint_type}">
  <parent link="body_link"/>
  <child link="${name}"/>
  <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
  <axis xyz="0 1 0"/>
  <limit effort="1000" velocity="1000"/>
  <dynamics damping="1.0" friction="1.0"/>
</joint>

  </xacro:macro>

  <!-- Instantiate wheels -->
  <xacro:wheel name="rear_right_wheel"  x="${-body_link_x_dim/2 + 1.2*wheel_link_radius}" y="${-body_link_y_dim/2 - 1.2*wheel_link_length/2}" z="${wheel_link_z_location}" joint_type="continuous"/>
  <xacro:wheel name="rear_left_wheel" x="${-body_link_x_dim/2 + 1.2*wheel_link_radius}" y="${body_link_y_dim/2 + 1.2*wheel_link_length/2}" z="${wheel_link_z_location}" joint_type="continuous"/>
  <xacro:wheel name="front_right_wheel" x="${body_link_x_dim/2 - 1.2*wheel_link_radius}" y="${-body_link_y_dim/2 - 1.2*wheel_link_length/2}" z="${wheel_link_z_location}" joint_type="continuous"/>
  <xacro:wheel name="front_left_wheel" x="${body_link_x_dim/2 - 1.2*wheel_link_radius}" y="${body_link_y_dim/2 + 1.2*wheel_link_length/2}" z="${wheel_link_z_location}" joint_type="continuous"/>

  <!-- TODO: Complete: Wheels must be named - rear_left_wheel, front_right_wheel, front_left_wheel -->

<!-- Camera -->
  <link name="camera_link">
    <visual>
      <geometry><box size="${sensor_side} ${sensor_side} ${sensor_side}"/></geometry>
      <origin rpy="0 0 0" xyz="0 0 0" />
    </visual>
    <collision>
      <geometry><box size="${sensor_side} ${sensor_side} ${sensor_side}"/></geometry>
      <origin rpy="0 0 0" xyz="0 0 0" />
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="${sensor_mass}"/>
      <inertia 
        ixx="1e-6" ixy="0.0" ixz="0.0"
        iyy="1e-6" iyz="0.0"
        izz="1e-6"/>
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <parent link="body_link"/>
    <child link="camera_link"/>
    <origin xyz="${-body_link_x_dim/4} 0 ${body_link_z_dim/2 + sensor_side/2}"/>
    <axis xyz="0 1 0" />
  </joint>


  <!-- Sonar -->
  <link name="sonar_link">
  <visual>
    <geometry><box size="${sensor_side} ${sensor_side} ${sensor_side}"/></geometry>
    <origin rpy="0 0 0" xyz="0 0 0" />
  </visual>
  <collision>
    <geometry><box size="${sensor_side} ${sensor_side} ${sensor_side}"/></geometry>
    <origin rpy="0 0 0" xyz="0 0 0" />
  </collision>
  <inertial>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <mass value="${sensor_mass}"/>
    <inertia ixx="1e-6" ixy="0.0" ixz="0.0" iyy="1e-6" iyz="0.0" izz="1e-6"/>
  </inertial>
</link>

<joint name="sonar_joint" type="fixed">
  <parent link="body_link"/>
  <child link="sonar_link"/>
  <origin xyz="0 ${body_link_y_dim/2 + sensor_side/2} ${body_link_z_dim/2}"/>
</joint>

<link name="lidar_link">
  <visual>
    <geometry><cylinder radius="0.05" length="0.1"/></geometry>
    <origin rpy="0 0 0" xyz="0 0 0" />
  </visual>
  <collision>
    <geometry><cylinder radius="0.05" length="0.1"/></geometry>
    <origin rpy="0 0 0" xyz="0 0 0" />
  </collision>
  <inertial>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <mass value="${sensor_mass}"/>
    <inertia ixx="1e-6" ixy="0.0" ixz="0.0" iyy="1e-6" iyz="0.0" izz="1e-6"/>
  </inertial>
</link>

<joint name="lidar_joint" type="fixed">
  <parent link="body_link"/>
  <child link="lidar_link"/>
  <origin xyz="0 0 ${body_link_z_dim/2 + 0.1}"/>
</joint>


</robot>
